services:
  - type: web
    name: fastapi-app
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "./start.sh"
    envVars:
      - key: SMTP_EMAIL
        value: "noreply.synergy.messenger@gmail.com"
      - key: SMTP_PASSWORD
        sync: false  # Set this manually in Render's dashboard
